name: pytorch

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda

dependencies: 
  - python=3.8
  - pandas
  - openpyxl
  - xlsxwriter
  - numpy
  - nibabel
  - networkx
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn
  - scikit-posthocs
  - umap-learn
  - hdbscan
  - matplotlib
  - seaborn
  - pyvis
  - dvc
  - dvc-ssh
  - ipykernel
  - pip
 

